project:
  type: website
  output-dir: docs

website:
  title: "Nathaniel D. Phillips, PhD"
  google-analytics: "G-H0ZF5JL7LN"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: resume.qmd
        text: Resume
      - text: Blog
        href: blog.qmd
      - href: contact.qmd
        text: Contact
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/nathanieldphillips/
      - icon: github
        href: https://github.com/ndphillips

format:
  html:
    theme: simplex
    toc: true
    fig-cap: true

theme:
  light: flatly
  dark: darkly

blog:
  exclude: ["draft: true"]
