project:
  type: website
  output-dir: docs

website:
  title: "Nathaniel D. Phillips, PhD"
  google-analytics: "G-H0ZF5JL7LN"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
   #   - href: blog.qmd
  #      text: Blog
      - href: resources.qmd
        text: Resources
      - href: personal.qmd
        text: Personal
      - href: contact.qmd
        text: Contact
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/nathanieldphillips/
      - icon: github
        href: https://github.com/ndphillips

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

theme:
  light: flatly
  dark: darkly
