---
title: "About"
---

## Principles

Here are my principles

1. Useful
2. Honest
3. Respectful
4. Resourceful

## Education

| Degree | Institution | Major | Note |
|--------|-------------|------|------|
| B.A.   | [Grinnell College](www.grinnell.edu)  | Mathematics | |
| M.S.   | [Ohio University](www.ohio.edu) | Experimental Psychology |    |
| Ph.D.  | [University of Basel](www.unibas.ch) | Cognitive Psychology | |

## Work Experience

Here is a selection of my work experience

| Position | Institution | Note |
|----------|-------------|------|
| Postdoc | [University of Konstanz](https://www.uni-konstanz.de/en/) | |
| Postdoc | [University of Basel](https://www.unibas.ch) | |
| Real World Data Scientist | [Roche](https://www.roche.com) | 
| Data Scientist | [Flatiron](https://www.flatiron.com) | 
| CTO, Co-Founder | [Plinth Analytics](https://www.plinth.co) | 

## Presentations

| Title | Conference |
|-------|------------|
| FlatironKitchen| RStudio Conf|
| 

## Publications

Here are the two publications I'm most proud of, see all of them at [Google Scholar](https://scholar.google.com/citations?user=ThWbpDQAAAAJ&hl=en)

| Title | Authors | Journal | Note |
|-------|---------|---------|------|
| [FFTrees: A toolbox to create, visualize, and evaluate fast-and-frugal decision trees](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=ThWbpDQAAAAJ&citation_for_view=ThWbpDQAAAAJ:9vf0nzSNQJEC) | Phillips, N.D., Neth, H., Woike, J.K., Gaissmaier, W. | Judgment and Decision Making | |
| [Rivals in the dark: How competition influences search in decisions under uncertainty](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=ThWbpDQAAAAJ&citation_for_view=ThWbpDQAAAAJ:2osOgNQ5qMEC) | ND Phillips, R Hertwig, Y Kareev, J Avrahami | Cognition | |

## Open Source Projects

Most of my projects are proprietary, but here are some open source projects that I contribute to

| Title | Description | Note |
|-------|-------------|------|
| [FFTrees](https://github.com/ndphillips/FFTrees) | A toolbox to create, visualize, and evaluate fast-and-frugal decision trees | |
| [yarrr](https://github.com/ndphillips/yarrr) | A package for creating pirate plots in R | |

